import type { Category } from "./types";

/** In home-page order. */
export const categories: Category[] = [
  {
    id: "laser-safety",
    label: "Laser Safety",
    title: "Laser Safety Calculators",
    description: "Educational laser safety calculators with explicit trust boundaries. Separate bounded CW point-source pre-check tools from general educational references and quarantined standards-heavy topics.",
    heading: "Laser Safety",
    keywords: ["laser safety", "mpe", "nohd", "od", "eyewear", "hazard"],
    priority: 55,
    home: {
      eyebrow: "Hazards & limits",
      description: "NOHD, MPE, OD calculations and eye safety tools.",
      hoverDescription: "Estimate hazard distances, exposure limits, optical density, and classification thresholds for safety-critical laser scenarios.",
      accentFrom: "#fb7185",
      accentTo: "#f59e0b",
      examples: ["MPE", "NOHD", "Optical density"],
    },
  },
  {
    id: "fiber-optics",
    label: "Fiber Optics",
    title: "Fiber Optics Calculators",
    description: "Fiber optics calculators for coupling, dispersion, bend loss, V-number, nonlinear thresholds, and guided-wave design.",
    heading: "Fiber Optics",
    intro: "Calculators for optical fiber propagation, coupling, and losses.",
    keywords: ["fiber", "mfd", "na", "dispersion", "splice", "coupling"],
    priority: 60,
    home: {
      eyebrow: "Guided light",
      description: "Attenuation, coupling, dispersion, nonlinear thresholds.",
      hoverDescription: "Explore how guided modes, attenuation, dispersion, coupling, and nonlinear effects shape fiber systems.",
      accentFrom: "#38bdf8",
      accentTo: "#2dd4bf",
      examples: ["Coupling efficiency", "Dispersion", "V-number"],
    },
  },
  {
    id: "thin-film",
    label: "Thin Film",
    title: "Thin Film Calculators",
    description: "Thin-film optics calculators for AR coatings, dielectric stacks, dichroics, reflectors, interference filters, and deposition effects.",
    heading: "Thin Film Optics",
    intro: "Calculators for thin film coatings, AR coatings, and dielectric stacks.",
    keywords: ["coating", "ar", "dielectric stack", "bragg", "reflectance"],
    priority: 60,
    home: {
      eyebrow: "Interference stacks",
      description: "AR coatings, dichroics, reflectors, stress and deposition.",
      hoverDescription: "Design multilayer stacks, anti-reflection coatings, filters, and angle-sensitive interference behavior.",
      accentFrom: "#a78bfa",
      accentTo: "#f472b6",
      examples: ["Single AR", "Bragg reflector", "Dichroic filter"],
    },
  },
  {
    id: "imaging",
    label: "Imaging",
    title: "Imaging Calculators",
    description: "Optical imaging calculators for resolution, PSF, depth of field, microscopy, OCT, and wavefront-driven imaging analysis.",
    heading: "Imaging & Microscopy",
    intro: "Resolution, contrast, depth of field, and optical system design calculators for microscopy.",
    keywords: ["resolution", "na", "microscopy", "airy", "mtf", "psf"],
    priority: 60,
    home: {
      eyebrow: "Focus & sensing",
      description: "Resolution, DOF, microscopy, OCT, focal geometry.",
      hoverDescription: "From PSF and depth of field to wavefront sensing and OCT coherence, model how optics form images.",
      accentFrom: "#60a5fa",
      accentTo: "#22d3ee",
      examples: ["Resolution", "Optical coherence", "PSF"],
    },
  },
  {
    id: "spectroscopy",
    label: "Spectroscopy",
    title: "Spectroscopy Calculators",
    description: "Spectroscopy calculators for FTIR, Raman, spectral resolution, calibration, line broadening, and signal analysis.",
    heading: "Spectroscopy",
    intro: "Calculators for spectrometer design, spectroscopy fundamentals, and signal analysis.",
    keywords: ["beer lambert", "ftir", "blackbody", "raman", "wavenumber"],
    priority: 60,
    home: {
      eyebrow: "Wavelength & signal",
      description: "Resolution, FTIR, Raman, line broadening, calibration.",
      hoverDescription: "Resolve spectra, calibrate dispersive systems, estimate line broadening, and reason about signal-to-noise.",
      accentFrom: "#c084fc",
      accentTo: "#f472b6",
      examples: ["FTIR resolution", "Raman shift", "Spectral calibration"],
    },
  },
  {
    id: "detectors",
    label: "Detectors",
    title: "Detectors Calculators",
    description: "Photonics detector calculators for responsivity, NEP, dark noise, SPADs, avalanche gain, and sensor performance.",
    heading: "Photodetectors",
    intro: "Calculators for photodetector performance metrics.",
    keywords: ["sensor", "noise", "qe", "responsivity", "nep", "detectivity"],
    priority: 40,
    home: {
      eyebrow: "Light to signal",
      description: "Responsivity, NEP, dark noise, avalanche gain, SPADs.",
      hoverDescription: "Understand how photons become current, noise, gain, and readout limits across detector families.",
      accentFrom: "#f59e0b",
      accentTo: "#f97316",
      examples: ["NEP", "Responsivity", "SPAD dead time"],
    },
  },
  {
    id: "materials",
    label: "Materials",
    title: "Optical Materials Calculators",
    description: "Optical materials calculators for refractive index, Sellmeier fits, thermal properties, absorption, and nonlinear material behavior.",
    heading: "Optical Materials",
    intro: "Calculators for optical material properties and surface interactions.",
    keywords: ["sellmeier", "dispersion", "glass", "index", "material properties"],
    priority: 60,
    home: {
      eyebrow: "Indices & media",
      description: "Sellmeier, dispersion, absorption, thermal and nonlinear properties.",
      hoverDescription: "Compare optical materials, refractive index models, absorption bands, and thermal or nonlinear behavior.",
      accentFrom: "#34d399",
      accentTo: "#22c55e",
      examples: ["Sellmeier", "Abbe number", "Transparency range"],
    },
  },
  {
    id: "wave-optics",
    label: "Wave Optics",
    title: "Wave Optics Calculators",
    description: "Wave optics calculators for Gaussian beams, cavities, diffraction, interferometers, nonlinear propagation, and laser resonators.",
    heading: "Wave Optics",
    intro: "Calculators for Gaussian beam propagation and ABCD matrix ray tracing.",
    keywords: ["gaussian beam", "abcd", "cavity", "mode matching", "diffraction"],
    priority: 60,
    home: {
      eyebrow: "Interference & propagation",
      description: "Gaussian beams, cavities, diffraction, combs, nonlinear propagation.",
      hoverDescription: "Follow phase, coherence, cavity stability, diffraction, and ultrafast propagation through wave-optics tools.",
      accentFrom: "#818cf8",
      accentTo: "#38bdf8",
      examples: ["Gaussian beam", "ABCD matrix", "Interferometer"],
    },
  },
  {
    id: "polarization",
    label: "Polarization",
    title: "Polarization Calculators",
    description: "Polarization calculators for Jones and Stokes analysis, retarders, birefringence, Mueller matrices, and waveplate design.",
    heading: "Polarization",
    intro: "Calculators for polarization states, birefringence, and polarization optics.",
    keywords: ["stokes", "jones", "mueller", "waveplate", "polarizer"],
    priority: 60,
    home: {
      eyebrow: "Vector states",
      description: "Jones, Stokes, retarders, birefringence and PMD.",
      hoverDescription: "Model polarization state evolution, retarders, Mueller/Jones formalisms, and birefringent systems.",
      accentFrom: "#f472b6",
      accentTo: "#fb7185",
      examples: ["Jones calculus", "Poincaré sphere", "Waveplate thickness"],
    },
  },
  {
    id: "free-space-comms",
    label: "Free-Space Comms",
    title: "Free-Space Optical Communications Calculators",
    description: "Free-space optics calculators for link budgets, pointing loss, scintillation, BER, weather attenuation, and optical comms.",
    heading: "Free-Space Communications",
    intro: "Calculators for free-space optical communication links.",
    keywords: ["fso", "link budget", "fog", "scintillation", "pointing"],
    priority: 40,
    home: {
      eyebrow: "Links through air",
      description: "Pointing loss, BER, scintillation, weather attenuation.",
      hoverDescription: "Estimate atmospheric penalties, pointing sensitivity, channel capacity, and link margins for optical links.",
      accentFrom: "#22d3ee",
      accentTo: "#a78bfa",
      examples: ["Link budget", "Pointing loss", "Scintillation"],
    },
  },
];
