import type { CalculatorEntry } from "../types";

export const materials: CalculatorEntry[] = [
  {
    slug: "abbe-number",
    title: "Abbe Number (Vd)",
    description: "Calculate Abbe number from Sellmeier coefficients. Vd = (nD - 1)/(nF - nC).",
  },
  {
    slug: "absorption",
    title: "Absorption Coefficient",
    description: "Wavelength-dependent absorption coefficient () and transmission through material thickness.",
    lede: "Wavelength-dependent absorption coefficient α(λ) and transmission through material thickness.",
  },
  {
    slug: "acousto-optic",
    title: "Acousto-Optic Materials",
    description: "Acousto-optic figure of merit, Bragg angle, and deflection calculations",
  },
  {
    slug: "aging-effects",
    title: "Aging of Optical Materials",
    description: "Long-term degradation: transmission loss, solarization, compaction, stress relaxation",
  },
  {
    slug: "birefringent-crystals",
    title: "Birefringent Crystals",
    description: "Ordinary (nₒ) and extraordinary (nₑ) refractive indices",
  },
  {
    slug: "brewster-tir",
    title: "Brewster Angle & Total Internal Reflection",
    description: "Interactive Brewster-angle and critical-angle explorer with common material presets.",
    lede: "Interactive Brewster-angle and critical-angle explorer with common interface presets.",
    related: [
      { href: "/materials/aging-effects" },
      { href: "/materials/birefringent-crystals" },
      { href: "/materials/brillouin-scattering" },
      { href: "/materials/calcite-properties" },
    ],
  },
  {
    slug: "brillouin-scattering",
    title: "Brillouin Scattering",
    description: "Stimulated Brillouin scattering (SBS): frequency shift, gain coefficient, and power threshold in optical fibers and bulk materials.",
  },
  {
    slug: "calcite-properties",
    title: "Calcite (CaCO₃) Properties",
    description: "Uniaxial negative crystal with the largest birefringence of common optical crystals. n 0.172 at 589nm.",
    lede: "Uniaxial negative crystal with the largest birefringence of common optical crystals. Δn ≈ 0.172 at 589nm.",
  },
  {
    slug: "chalcogenide-glass",
    title: "Chalcogenide Glass Properties",
    description: "IR-transparent glasses for thermal imaging, sensing, and nonlinear optics",
  },
  {
    slug: "chromatic-dispersion",
    title: "Chromatic Dispersion",
    description: "Material dispersion dn/d from Sellmeier coefficients",
    lede: "Material dispersion dn/dλ from Sellmeier coefficients",
  },
  {
    slug: "coefficient-thermal-expansion",
    title: "Coefficient of Thermal Expansion",
    description: "Thermal expansion of optical materials",
  },
  {
    slug: "color-centers",
    title: "Color Centers in Crystals",
    description: "Point defects and impurity centers: absorption/emission spectra, cross-sections, and ZPL characteristics. Key for quantum emitters and tunable lasers.",
  },
  {
    slug: "contamination",
    title: "Contamination Effects",
    description: "Particle contamination impact on optical surfaces",
  },
  {
    slug: "crystal-birefringence",
    title: "Crystal Birefringence Data",
    description: "n = |nₒ − nₑ| for uniaxial and birefringent crystals at selected wavelength",
    lede: "Δn = |nₒ − nₑ| for uniaxial and birefringent crystals at selected wavelength",
  },
  {
    slug: "damage-threshold",
    title: "Laser Damage Threshold",
    description: "LIDT for pulsed and CW laser optics",
  },
  {
    slug: "diamond-optics",
    title: "Diamond Optics",
    description: "Diamond — the ultimate optical material. Bandgap: 5.47 eV. n 2.42.",
    lede: "Diamond — the ultimate optical material. Bandgap: 5.47 eV. n ≈ 2.42.",
  },
  {
    slug: "electro-optic",
    title: "Electro-Optic Coefficients",
    description: "Pockels effect materials for modulators, Q-switches, and phase shifters",
  },
  {
    slug: "fluoride-glass",
    title: "Fluoride Glass (ZBLAN)",
    description: "Heavy-metal fluoride glasses for mid-IR fiber optics and low-loss transmission",
  },
  {
    slug: "fresnel",
    title: "Fresnel Equations",
    description: "Interactive Fresnel reflection and transmission at a dielectric interface with sliders, presets, and angle sweeps.",
    lede: "Reflection and transmission at a dielectric interface with angle sweeps, presets, and polarization split.",
    related: [
      { href: "/materials/electro-optic" },
      { href: "/materials/fluoride-glass" },
      { href: "/materials/group-index" },
      { href: "/materials/gvd" },
    ],
  },
  {
    slug: "group-index",
    title: "Group Index (ng)",
    description: "ng = n − dn/d — the effective index seen by optical pulses",
    lede: "ng = n − λ · dn/dλ — the effective index seen by optical pulses",
  },
  {
    slug: "gvd",
    title: "Group Velocity Dispersion (GVD)",
    description: "Calculate d²n/d² and dispersion parameter from Sellmeier coefficients.",
    lede: "Calculate d²n/dλ² and β₂ dispersion parameter from Sellmeier coefficients.",
  },
  {
    slug: "heat-capacity",
    title: "Heat Capacity of Optical Materials",
    description: "Specific heat and thermal energy storage",
  },
  {
    slug: "humidity-effects",
    title: "Humidity Effects on Optics",
    description: "Water absorption, refractive index changes, and surface degradation",
  },
  {
    slug: "infrared-glass",
    title: "Infrared Optical Materials",
    description: "Compare IR transmitting materials. n(T) = n₅ + (dn/dT)(T - 25°C)",
    lede: "Compare IR transmitting materials. n(T) = n₂₅ + (dn/dT)(T - 25°C)",
  },
  {
    slug: "infrared-materials",
    title: "Infrared Materials",
    description: "Ge, Si, ZnSe, chalcogenides — refractive index and properties for IR optics",
  },
  {
    slug: "magneto-optic",
    title: "Magneto-Optic Materials",
    description: "Faraday rotation, Verdet constants, and isolator design calculations",
  },
  {
    slug: "nonlinear-crystals",
    title: "Nonlinear Crystal Comparison",
    description: "SHG, OPO, and frequency conversion crystal properties",
  },
  {
    slug: "nonlinear-index",
    title: "Nonlinear Refractive Index (n)",
    description: "Kerr effect: n = n I, where I is the optical intensity",
    heading: "Nonlinear Refractive Index (n₂)",
    lede: "Kerr effect: Δn = n₂ · I, where I is the optical intensity",
  },
  {
    slug: "oh-absorption",
    title: "OH Absorption in Silica",
    description: "Hydroxyl (OH⁻) absorption peaks in silica fibers and bulk glass. The fundamental OH stretch at 2.72 µm and overtones at 1.38 µm and 0.94 µm dominate loss spectra.",
  },
  {
    slug: "optical-glass-catalog",
    title: "Optical Glass Catalog",
    description: "Interactive glass map and dispersion curves. Sellmeier: n²() = 1 + Σ Bi²/(² - Ci)",
    lede: "Interactive glass map and dispersion curves. Sellmeier: n²(λ) = 1 + Σ Biλ²/(λ² - Ci)",
  },
  {
    slug: "photoelastic",
    title: "Photoelastic Constants",
    description: "Stress-induced birefringence: n = C , where C is the stress-optic coefficient",
    lede: "Stress-induced birefringence: Δn = C · σ, where C is the stress-optic coefficient",
  },
  {
    slug: "photorefractive",
    title: "Photorefractive Effect",
    description: "Light-induced refractive index changes via space-charge fields in electro-optic materials. Key for holographic storage, phase conjugation, and beam coupling.",
  },
  {
    slug: "polymer-optics",
    title: "Polymer Optical Materials",
    description: "Refractive index, dispersion, and loss data for optical polymers",
  },
  {
    slug: "quartz-crystal",
    title: "Quartz Crystal (SiO) Properties",
    description: "Uniaxial positive, optically active, piezoelectric. Sellmeier dispersion for o & e rays.",
    heading: "Quartz Crystal (SiO₂) Properties",
  },
  {
    slug: "radiation-damage",
    title: "Radiation Damage Effects",
    description: "Radiation-induced absorption and transmission loss in optical materials",
  },
  {
    slug: "raman-scattering",
    title: "Raman Scattering",
    description: "Spontaneous and stimulated Raman scattering cross-sections and gain spectra for common optical materials.",
  },
  {
    slug: "rare-earth-absorption",
    title: "Rare Earth Absorption Spectra",
    description: "Absorption cross-sections for common rare-earth dopants in silica: Er³⁺, Nd³⁺, Yb³⁺, Tm³⁺, Ho³⁺.",
  },
  {
    slug: "sapphire-properties",
    title: "Sapphire (AlO₃) Properties",
    description: "Uniaxial crystal. Sellmeier equations for ordinary and extraordinary rays.",
    heading: "Sapphire (Al₂O₃) Properties",
  },
  {
    slug: "schott-glass",
    title: "Schott Glass Catalog",
    description: "Refractive index n() from SCHOTT Sellmeier coefficients",
    lede: "Refractive index n(λ) from SCHOTT Sellmeier coefficients",
  },
  {
    slug: "sellmeier",
    title: "Sellmeier Equation",
    description: "Calculate refractive index from Sellmeier coefficients across wavelength.",
    lede: "Interactive dispersion explorer using Sellmeier coefficients to compute refractive index versus wavelength.",
    keywords: ["dispersion formula", "refractive index", "glass catalog"],
    priority: 94,
    related: [
      { href: "/materials/sapphire-properties" },
      { href: "/materials/schott-glass" },
      { href: "/materials/semiconductor-bandgap" },
      { href: "/materials/thermal-conductivity-optics" },
    ],
  },
  {
    slug: "semiconductor-bandgap",
    title: "Semiconductor Bandgap",
    description: "Bandgap energy and absorption edge vs temperature using the Varshni equation. Direct vs indirect gap materials.",
  },
  {
    slug: "thermal-conductivity-optics",
    title: "Thermal Conductivity for Optics",
    description: "Heat transport in optical substrates",
  },
  {
    slug: "thermal-dndt",
    title: "Thermo-Optic Coefficient (dn/dT)",
    description: "Temperature-dependent refractive index change. Positive dn/dT means n increases with temperature.",
  },
  {
    slug: "thermal-expansion",
    title: "Thermal Expansion",
    description: "L = T L — dimensional change from temperature",
    lede: "ΔL = α · ΔT · L — dimensional change from temperature",
  },
  {
    slug: "transparency-range",
    title: "Transparency Range",
    description: "UV cutoff to IR cutoff for common optical materials",
  },
  {
    slug: "two-photon-absorption",
    title: "Two-Photon Absorption",
    description: "Nonlinear absorption coefficient PA and intensity-dependent transmission. TPA becomes significant at high peak intensities (pulsed lasers).",
    lede: "Nonlinear absorption coefficient β₂PA and intensity-dependent transmission. TPA becomes significant at high peak intensities (pulsed lasers).",
  },
  {
    slug: "uv-materials",
    title: "UV Optical Materials",
    description: "Deep UV to near-UV materials comparison. Sellmeier: n² = 1 + Σ Bi²/(² - Ci)",
    lede: "Deep UV to near-UV materials comparison. Sellmeier: n² = 1 + Σ Biλ²/(λ² - Ci)",
  },
  {
    slug: "verdet-constant",
    title: "Verdet Constant",
    description: "Faraday rotation: = V B L, where V ∝ 1/² for paramagnetic materials",
    lede: "Faraday rotation: θ = V · B · L, where V ∝ 1/λ² for paramagnetic materials",
  },
  {
    slug: "x-ray-optics",
    title: "X-ray Optics Materials",
    description: "X-ray refractive index: n = 1 - - i. For hard X-rays, , ∝ ² ∝ 1/E².",
    lede: "X-ray refractive index: n = 1 - δ - iβ. For hard X-rays, δ,β ∝ λ² ∝ 1/E².",
  },
];
